CREATE TABLE `link` (id TEXT NOT NULL UNIQUE, redirect TEXT NOT NULL, category TEXT NOT NULL);

CREATE TABLE `bot` (id TEXT NOT NULL UNIQUE, redirect TEXT NOT NULL);

CREATE TABLE `server` (id TEXT NOT NULL UNIQUE, redirect TEXT NOT NULL);

CREATE TABLE `user` (id TEXT NOT NULL UNIQUE, redirect TEXT NOT NULL);
